# Generated by Django 5.0.1 on 2024-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muladmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='quanttity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
