# Generated by Django 5.0.1 on 2024-04-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user_cart_customer'),
        ('product', '0016_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='inventory',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='product.inventory'),
            preserve_default=False,
        ),
    ]
