# Generated by Django 5.0.1 on 2024-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id_default',
            field=models.BooleanField(default=False),
        ),
    ]
