# Generated by Django 5.0.1 on 2024-04-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_address_id_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id_default',
            new_name='is_default',
        ),
    ]
