# Generated by Django 5.0.1 on 2024-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_id_default_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
