# Generated by Django 5.0.1 on 2024-04-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
