# Generated by Django 5.0.1 on 2024-05-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_order_status_alter_orderitem_status_and_more'),
        ('muladmin', '0002_rename_quanttity_coupon_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muladmin.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
