# Generated by Django 5.0.1 on 2024-05-23 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid name.', regex='^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$')]),
        ),
    ]
