# Generated by Django 5.0.1 on 2024-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
