# Generated by Django 5.0.1 on 2024-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
