# Generated by Django 5.0.1 on 2024-02-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_image_product_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='subcategory_products', to='product.category'),
        ),
    ]
