# Generated by Django 5.0.1 on 2024-02-23 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
