# Generated by Django 5.0.1 on 2024-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_account_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/user/customer/profile_image'),
        ),
    ]
